modLoader = "javafml"
loaderVersion = "[45,)"
issueTrackerURL = "https://github.com/FakeACat/FromAnotherWorld/issues"
license = "MIT"

[[mods]]
modId = "fromanotherworld"
version = "${version}"
displayName = "From Another World"
authors = "a cats (code, models, textures), ImpulsiveLass (Palmer Thing model and texture), techno_theprotogen (Impaler Llama model)"
description = '''
adds the thing from the thing
'''
logoFile = "assets/fromanotherworld/icon.png"

[[dependencies.fromanotherworld]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fromanotherworld]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fromanotherworld]]
modId = "azurelib"
mandatory = true
versionRange="[1.0.15,)"
ordering = "NONE"
side = "BOTH"